# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: CC0-1.0
#
# Configuration for Vale prose linter
#
# See https://vale.sh for more information.

StylesPath = .vale/styles

MinAlertLevel = suggestion

Packages = write-good

[*.md]
BasedOnStyles = Vale, write-good
