# SPDX-FileCopyrightText: 2024-present Stuart Ellis <stuart@stuartellis.name>
#
# SPDX-License-Identifier: MIT
#
# Tasks for the Task runner:
#
# https://taskfile.dev/

version: "3.38"

silent: true

includes:
  hugo: .tasks/shared/hugo
  pre-commit: .tasks/shared/pre-commit
  project:
    taskfile: .tasks/project
    flatten: true
  vale: .tasks/shared/vale

tasks:
  default:
    cmds:
      - task: list

  list:
    desc: List available tasks
    cmds:
      - "{{.TASK_EXE}} --list"
